[package]
name = "audiacore-host-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
audiacore-host = { path = "../audiacore-host" }

[dev-dependencies]
audiacore-sensitive = { path = "../audiacore-sensitive" }
cap-std = { workspace = true }
